### ISSUE TITLE
CD/CI output format.

### ISSUE THREAD

**Issue by denzyldick** [denzyldick/phanalist#41]
To successfully implement Phanalist into a CI/CD pipeline Phanalist should be able to format the output into different formats that are supported by all of the major CI/CD platforms. 

These formats are:

- [ ] checkstyle
- [ ] junit
- [ ] github
- [ ] gitlab

**Comment by SerheyDolgushev** [comment]
Right now, Phanalist returns 0 exit code if no violations were found, and 70 exit code if any violations were found: https://github.com/denzyldick/phanalist/blob/4ebc62711e60b0d277846859f96ed55dbf1c8cd4/src/main.rs#L69-L73. And the main intention for this was to use it in CI/CD integrations. Do you think, in addition to this, we should return the data about found violations in CI/CD-specific format?
