### ISSUE TITLE
Traversing

### ISSUE THREAD

**Issue by denzyldick** [denzyldick/phanalist#48]
At the time of writing this issue, I can feel that I'm duplicating some sections of the rules. 
For example, the code below has already been written twice. 

```rs
fn validate(){
 if let Statement::Class(class) = self.statement {
            for member in &class.body.members {
                if let ClassMember::ConcreteMethod(concretemethod) = member {
                    let MethodBody {
                        comments: _,
                        left_brace: _,
                        statements,
                        right_brace: _,
                    } = &concretemethod.body;
                    {
                        /// Execute logic.
                    }
                }
            }
        }

}
```
I need to create a way to reuse it. There should be a function  `find_members_and_execute` or something like that.

**Comment by SerheyDolgushev** [comment]
As part of https://github.com/denzyldick/phanalist/issues/47 I will do a refactoring and will try to submit it during the weekend. Let's get back to it afterward.
